### ISSUE TITLE
Change the background to a gray color overlay

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/ds_brexit#4]
I wanna pretty much just replicate how we do modals on the main site instead of just grayscaling the background.

Specifically darkening the background with an overlay. Keep the blur the same (2px) though if possible.

![screen shot 2016-06-29 at 11 15 19 am](https://cloud.githubusercontent.com/assets/1865372/16457891/294c835a-3deb-11e6-9ee8-23856574fb5f.png)
![screen shot 2016-06-29 at 11 17 28 am](https://cloud.githubusercontent.com/assets/1865372/16457893/2c33b048-3deb-11e6-9b9a-41b1c27f1006.png)

**Comment by itsjoekent** [comment]
ah gotcha, sure thing

**Comment by itsjoekent** [comment]
<img width="1298" alt="screen shot 2016-06-29 at 1 51 31 pm" src="https://cloud.githubusercontent.com/assets/897368/16462736/9f0bd2a2-3e00-11e6-814d-861673277e7b.png">

**Comment by itsjoekent** [comment]
https://github.com/DoSomething/ds_brexit/commit/d92174ec0826abbd2e07c38daf68a3ba10bf7d1e
